---
# role: ansible-role-sysctl
# file: tasks/main.yml

- name: "Role sysctl | install packages"
  ansible.builtin.package:
    name: "{{ sysctl_packages }}"
    state: present

- name: "Role sysctl | configure /etc/sysctl.conf"
  ansible.builtin.template:
    src: etc/sysctl.conf.j2
    dest: /etc/sysctl.conf
    mode: "0640"
    owner: root
    group: root
    backup: "{{ sysctl_backup }}"
  when: sysctl_conf | length > 0
  notify: reload sysctl

- name: "Role sysctl | ensure /etc/sysctl.d/"
  ansible.builtin.file:
    path: /etc/sysctl.d/
    state: directory
    mode: "0750"
    owner: root
    group: root

- name: "Role sysctl | configure /etc/sysctl.d/ files"
  ansible.builtin.template:
    src: etc/sysctl.d/sysctl.d.conf.j2
    dest: "/etc/sysctl.d/{{ item.file }}"
    mode: "0640"
    owner: root
    group: root
    backup: "{{ sysctl_backup }}"
  loop: "{{ sysctl_d }}"
  notify: "Reload sysctl"
