---
# role: jomrr.sysctl
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
  parallel: true
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: almalinux-sysctl
    box: "almalinux/9"
    cpus: 2
    memory: 2048
  - name: debian-sysctl
    box: "debian/bookworm64"
    cpus: 2
    memory: 2048
  - name: fedora-sysctl
    box: "fedora/40-cloud-base"
    cpus: 2
    memory: 2048
  - name: ubuntu-sysctl
    box: "cloud-image/ubuntu-24.04"
    cpus: 2
    memory: 2048
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
